name: Prettier check

on:
  pull_request:
    paths:
      - apps/expo-app/**

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: yarn

      - name: ✨ Run Prettier check
        run: yarn --cwd apps/expo-app prettier:check
