name: Run Jest tests

on:
  pull_request: 
    paths:
      - apps/expo-app/**

jobs:
   jest:
      name: Jest
      runs-on: ubuntu-latest
      steps:
         - name: 🏗 Setup repo
           uses: actions/checkout@v4

         - name: 📦 Install dependencies
           run: yarn

         - name: 🎭 Run Jest
           run: yarn --cwd apps/expo-app test
