name: Run Typescript

on:
  pull_request: 
    paths:
      - apps/expo-app/**

jobs:
   typescript-check:
      name: Typescript check
      runs-on: ubuntu-latest
      steps:
         - name: 🏗 Setup repo
           uses: actions/checkout@v4

         - name: 📦 Install dependencies
           run: yarn

         - name: 🔍 Run Typescript check
           run: yarn --cwd apps/expo-app ts:check
